version: '3.7'

services:
  app_proxy:
    environment:
      APP_HOST: epsilon-emby_server_1
      APP_PORT: 8096
      PROXY_AUTH_ADD: "false"

  server:
    image: xinjiawei1/emby_unlockd:4.10.0.40@sha256:285461fc4fec55724c054b435d2a51bcfacc2ecd6c34fcaa155b4943bff25ba4
    environment:
      TZ: Europe/Moscow
      UID: 1000
      GID: 1000
    restart: on-failure
    volumes:
      - ${APP_DATA_DIR}/data/config:/config:rw
      - ${UMBREL_ROOT}/data/storage/downloads:/downloads
