version: "3.7"

services:
  app_proxy:
    environment:
      APP_HOST: epsilon-atvloadly_server_1
      APP_PORT: 80

  server:
    image: ghcr.io/bitxeno/atvloadly:v0.6.1@sha256:a08e35e59bd30cd10fab594f938435116a6e96fab6b0c1d5d6ebc877dfa50bea
    restart: on-failure
    stop_grace_period: 30s
    security_opt:
      - seccomp:unconfined
    environment:
      SERVICE_PORT: "80"
      TZ: Europe/Moscow
    volumes:
      - ${APP_DATA_DIR}/data:/data
      - /var/run/dbus:/var/run/dbus
      - /var/run/avahi-daemon:/var/run/avahi-daemon
    healthcheck:
      test: ["CMD", "curl", "-f", "http://127.0.0.1:80/"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s
