version: "3.7"

services:
  app_proxy:
    environment:
      APP_HOST: epsilon-suwayomi_server_1
      APP_PORT: 4567

  server:
    image: ghcr.io/suwayomi/suwayomi-server:preview@sha256:2e709b5baffc1a72381a731a8b8b8d68be888d5e48d4e182600c7e180f84d4bf
    restart: on-failure
    stop_grace_period: 1m
    environment:
      - TZ=Europe/Moscow
    volumes:
      - ${APP_DATA_DIR}/data/downloads:/home/suwayomi/.local/share/Tachidesk/downloads
      - ${APP_DATA_DIR}/data:/home/suwayomi/.local/share/Tachidesk
