version: "3.7"

services:
  app_proxy:
    environment:
      APP_HOST: epsilon-suwayomi_server_1
      APP_PORT: 4567

  server:
    image: ghcr.io/suwayomi/suwayomi-server:preview@sha256:382e5dac9924efddcc49a258be93bb173b6e1976f6a69e434f61e14acd00bf5c
    restart: on-failure
    stop_grace_period: 1m
    environment:
      - TZ=Europe/Moscow
    volumes:
      - ${APP_DATA_DIR}/data/downloads:/home/suwayomi/.local/share/Tachidesk/downloads
      - ${APP_DATA_DIR}/data:/home/suwayomi/.local/share/Tachidesk
